export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const FETCH_HOMES_BEGIN   = 'FETCH_HOMES_BEGIN';
export const FETCH_HOMES_SUCCESS = 'FETCH_HOMES_SUCCESS';
export const FETCH_HOMES_FAILURE = 'FETCH_HOMES_FAILURE';

export const GET_VILLAGE_BEGIN   = 'GET_VILLAGE_BEGIN';
export const GET_VILLAGE_SUCCESS = 'GET_VILLAGE_SUCCESS';
export const GET_VILLAGE_FAILURE = 'GET_VILLAGE_FAILURE';
export const SET_CURRENT_V = 'SET_CURRENT_V';
